name: solidity-unit-testing-action
on: [push]

jobs:
  run_sample_test_job:
    runs-on: ubuntu-latest
    name: A job to run sample solidity tests
    steps:
      - name: Run SUT Action
        uses: EthereumRemix/sol-test@v1
        with:
            test-path: 'tests/Ballot_test.sol'
            compiler-version: '0.8.15'